ci: Do not test for Python 3.3. Numpy packages are not available.
If really needed, we could look into specifying some more complex
requirements using Environment Markers [1]

[1] https://www.python.org/dev/peps/pep-0496/

This commit avoids to get the following error:

Collecting numpy>=1.9.2 (from -r requirements.txt (line 1))
  Downloading numpy-1.12.0.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 240kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7w8sbj/numpy/setup.py", line 34, in <module>
        raise RuntimeError("Python version 2.7 or >= 3.4 required.")
    RuntimeError: Python version 2.7 or >= 3.4 required.

Reported-by: Joost van Griethuysen <j.v.griethuysen@nki.nl>